### ISSUE TITLE
Image button as target

### ISSUE THREAD

**Issue by Ketsuko** [aromajoin/material-showcase-ios#17]
Hey everyone, 
I'm trying to use the material showcase library with an image button as the target. 
However, when my app starts, the button is replaced with a plain color blue version of it, hiding all the details of the image... I tried to change the color parameters to clear or even comment some of them, but it didn't fix it. The image is still replaced by a plain color version of itself... 
Is it the way the library is intended to work?

Thanks for your help!

**Comment by quangctkm9207** [comment]
Hi,
Can you give me a screenshot?

**Comment by rebe1one** [comment]
@Ketsuko This happens because if you target an image and set the tint colour, it will change all non-transparent pixels to that tint colour. This is expected behaviour in the latest released version, but if you work off the latest master, there is a shouldSetTintColor flag you can set to false and it should resolve your issue.

**Comment by quangctkm9207** [comment]
@rebe1one : I really appreciated your time. It works well.
@Ketsuko: New version 0.3.0 is now available on [CocoaPod](https://cocoapods.org/pods/MaterialShowcase).
I updated the sample app with image button too, you might check it out. 
#0fd3cea
