### ISSUE TITLE
Multiline text goes out of screen

### ISSUE THREAD

**Issue by riserpete** [aromajoin/material-showcase-ios#2]
Hey,

great library! :)

I am having troubles with the secondaryText (primaryText might be affected is well). If the string is too long, the text goes off screen instead of line-breaking to a second line.

Cheers

**Comment by joshoconnor89** [comment]
my pull request fixes this too.  All you have to do is add \n when you want the line break:

showCase.secondaryText = "Click here to open the left menu where \nyou can change user, team, and \nsettings."

**Comment by quangctkm9207** [comment]
@riserpete : Thank you for checking it out. 
Please excuse the delay in my response.  Please check @joshoconnor89 new update.

**Comment by pbenkoe** [comment]
Thank you for the response! :)

Since apps might be localized in many languages, one can't fill in the necessary \n cases everywhere and also the strings wouldn't become reusable. Maybe this should be handled by the system? i.e. numberOfLines of UILabel set to 0 and give it a frame / work with AutoLayout..?

Best

**Comment by quangctkm9207** [comment]
The reason is that I calculate text frame size by mistake. I have fixed it with the newest commit and push patch version on CocoaPods.
