### ISSUE TITLE
Move the instructionView frame (y position)

### ISSUE THREAD

**Issue by mal3k** [aromajoin/material-showcase-ios#28]
Hi,

Is there a way to move the Y position of the instructionView?  Now it's fixed whatever the targetHolderRadius is. Which is not practical since the holder circle can overlap the text when its radius is big.

Thanks

**Comment by quangctkm9207** [comment]
Hi,
instructionView's position is currently calculated automatically based on targetView position.
If we want to change it explicitly, we need to change our design to expose new APIs.
But as I think, if it is displayed incorrectly when targetHolderRadius is large, we should fix the issue instead of exposing an API in which users have to fix by themselves. 
Can you give me an screenshot and detail which shows the problem occurred with a big holder radius? It helps a lot to dig deeper into it.

**Comment by happiehappie** [comment]
![simulator screen shot - iphone se - 2018-03-30 at 14 47 38](https://user-images.githubusercontent.com/6497131/38127733-098c53a6-342a-11e8-998f-da36972706ba.png)

Targetholderradius = view.frame.width / 2 + 8, it clearly overlaps the instruction view
