### ISSUE TITLE
Custom target view 

### ISSUE THREAD

**Issue by Prasanta022** [aromajoin/material-showcase-ios#5]
Hi,

If my target view inside the custom view which is added in the UIViewController's view then it's target view drawn outside the custom view. It's working fine in case of navigation item.

**Comment by quangctkm9207** [comment]
Hi @Prasanta022 ,
Please excuse me for replying late. 
Can you post the screenshot along? it is helpful to detect bugs visually.

**Comment by calvinsug** [comment]
here's the screenshoot for UI bug for Action 1 in your sample app
[http://res.cloudinary.com/duv544lom/image/upload/v1501063393/Screen_Shot_2017-07-26_at_4.57.18_PM_wlua4e.png](UIButton bug when i set width or height constraint)

[http://res.cloudinary.com/duv544lom/image/upload/v1501063392/Screen_Shot_2017-07-26_at_4.59.46_PM_ev8wre.png](it works if i remove width or height constraint)

it happens when i set width or height constraint to UIButton
