### ISSUE TITLE
Autolayout to UIButton not focus properly

### ISSUE THREAD

**Issue by GaneshKumarGk** [aromajoin/material-showcase-ios#6]
**Issues :**

When I set an auto layout to UIButton, the background image of the UIButton will be displayed on the top left corner of the screen instead of that correct original position.

Please give me suggestion for that

**Comment by quangctkm9207** [comment]
Hi @GaneshKumarGk,
Please give the screenshot. It's useful to detect UI issue. Thanks.

**Comment by calvinsug** [comment]
here's the screenshoot for UI bug for Action 1 in your sample app

[UIButton bug when i set width or height constraint, copied UIButton will be displayed on the top left corner of the screen instead of that correct original position](http://res.cloudinary.com/duv544lom/image/upload/v1501063393/Screen_Shot_2017-07-26_at_4.57.18_PM_wlua4e.png)


[it works if i remove width or height constraint](http://res.cloudinary.com/duv544lom/image/upload/v1501063392/Screen_Shot_2017-07-26_at_4.59.46_PM_ev8wre.png)

it happens when i set width or height constraint to UIButton

**Comment by florianhidayat** [comment]
I managed to fix the bug myself
@quangctkm9207 I've created a pull request for ya
#8

**Comment by quangctkm9207** [comment]
@florianhidayat , thank you for your time.
Merged already👍 
@calvinsug , @GaneshKumarGk Please check the new source code and feel free to open this thread if it is not solved completely.
