### ISSUE TITLE
swift 4 support

### ISSUE THREAD

**Issue by vre142** [aromajoin/material-showcase-ios#84]
Hi how can I use it in swift 4 and xcode 9?
can you give me a solution for it?
Thanks,
Vafa

**Comment by Husseinhj** [comment]
> Hi how can I use it in swift 4 and Xcode 9?

Basically for using the last version of the library you can't. Because the [last version](https://github.com/aromajoin/material-showcase-ios/blob/master/CHANGELOG.md#version-064-2018-11-10) of the library supports swift 4.2.

But you can use [0.6.2](https://github.com/aromajoin/material-showcase-ios/blob/master/CHANGELOG.md#version-062-2018-07-18) version it supports swift 3.
